#!/bin/sh
mkdir html && mkdir scss
cd html && touch index.html
cd ./../scss && touch style.scss
echo "*,
*::before,
*::after {
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}

html {
  font-size: 62.5%;
}" > style.scss